/**
 * Turn a curriculum CSV export from the old project into seed SQL for this one.
 *
 *   bun scripts/seed-curriculum.ts topics.csv spec_points.csv > supabase/seed_curriculum.sql
 *
 * Get the two CSVs from Anglian's Supabase SQL editor ("Download CSV" on the
 * result grid):
 *
 *   select id, subject, board, level, title, sort_order from topics order by id;
 *   select id, topic_id, code, title, sort_order, weight, video_url
 *     from spec_points order by topic_id, sort_order;
 *
 * The original UUIDs are kept rather than regenerated. That is what preserves
 * the topic → spec point mapping across the two files without this script
 * having to hold both in memory at once, and it makes re-running the seed
 * idempotent: `on conflict (id) do nothing` means a second run is a no-op
 * rather than a duplicate curriculum.
 *
 * Rows are streamed and escaped here, so thousands of spec points never pass
 * through a model's context — the whole reason this is a script and not a
 * conversation.
 */
import { createReadStream } from "node:fs";
import { createInterface } from "node:readline";

/** Minimal RFC-4180 line parser: handles quoted fields and doubled quotes. */
function parseCsvLine(line: string): string[] {
  const out: string[] = [];
  let field = "";
  let quoted = false;

  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (quoted) {
      if (c === '"') {
        if (line[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          quoted = false;
        }
      } else {
        field += c;
      }
    } else if (c === '"') {
      quoted = true;
    } else if (c === ",") {
      out.push(field);
      field = "";
    } else {
      field += c;
    }
  }
  out.push(field);
  return out;
}

/** A SQL literal, or NULL for an empty cell. */
function lit(v: string | undefined): string {
  if (v === undefined || v === "") return "null";
  return `'${v.replace(/'/g, "''")}'`;
}

function num(v: string | undefined, fallback: string): string {
  if (v === undefined || v === "" || Number.isNaN(Number(v))) return fallback;
  return String(Number(v));
}

async function emit(path: string, onRow: (row: Record<string, string>) => string) {
  const rl = createInterface({ input: createReadStream(path), crlfDelay: Infinity });
  let header: string[] | null = null;
  let count = 0;

  for await (const line of rl) {
    if (line.trim() === "") continue;
    const cells = parseCsvLine(line);
    if (!header) {
      header = cells.map((h) => h.trim().replace(/^"|"$/g, ""));
      continue;
    }
    const row: Record<string, string> = {};
    header.forEach((h, i) => (row[h] = cells[i] ?? ""));
    console.log(onRow(row));
    count++;
  }
  return count;
}

const [topicsCsv, specPointsCsv] = process.argv.slice(2);
if (!topicsCsv || !specPointsCsv) {
  console.error("usage: bun scripts/seed-curriculum.ts <topics.csv> <spec_points.csv>");
  process.exit(1);
}

console.log("-- Generated by scripts/seed-curriculum.ts. Do not edit by hand.");
console.log("-- Safe to re-run: every insert is `on conflict (id) do nothing`.");
console.log("begin;");
console.log();

const topics = await emit(
  topicsCsv,
  (r) =>
    `insert into public.topics (id, subject, board, level, title, sort_order) values (` +
    `${lit(r.id)}, ${lit(r.subject)}::public.subject, ${lit(r.board)}::public.board, ` +
    `${lit(r.level)}::public.level, ${lit(r.title)}, ${num(r.sort_order, "0")}) ` +
    `on conflict (id) do nothing;`,
);

console.log();

const points = await emit(
  specPointsCsv,
  (r) =>
    `insert into public.spec_points (id, topic_id, code, title, sort_order, weight, video_url) values (` +
    `${lit(r.id)}, ${lit(r.topic_id)}, ${lit(r.code)}, ${lit(r.title)}, ` +
    `${num(r.sort_order, "0")}, ${num(r.weight, "1")}, ${lit(r.video_url)}) ` +
    `on conflict (id) do nothing;`,
);

console.log();
console.log("commit;");
console.error(`Wrote ${topics} topics and ${points} spec points.`);
