/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppCurriculumRouteImport } from './routes/_app/curriculum'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppPlanRouteImport } from './routes/_app/plan'
import { Route as AppPlannerRouteImport } from './routes/_app/planner'
import { Route as AppSortRouteImport } from './routes/_app/sort'
import { Route as AppTutorRouteImport } from './routes/_app/tutor'
import { Route as AppHomeworkIndexRouteImport } from './routes/_app/homework.index'
import { Route as AppHomeworkAssignmentIdRouteImport } from './routes/_app/homework.$assignmentId'
import { Route as AppTutorIndexRouteImport } from './routes/_app/tutor.index'
import { Route as AppTutorCurriculumRouteImport } from './routes/_app/tutor.curriculum'
import { Route as AppTutorMarkingRouteImport } from './routes/_app/tutor.marking'
import { Route as AppTutorResourcesRouteImport } from './routes/_app/tutor.resources'
import { Route as AppTutorStudentsStudentIdRouteImport } from './routes/_app/tutor.students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCurriculumRoute = AppCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppSortRoute = AppSortRouteImport.update({
  id: '/sort',
  path: '/sort',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeworkIndexRoute = AppHomeworkIndexRouteImport.update({
  id: '/homework/',
  path: '/homework/',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeworkAssignmentIdRoute = AppHomeworkAssignmentIdRouteImport.update({
  id: '/homework/$assignmentId',
  path: '/homework/$assignmentId',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorIndexRoute = AppTutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTutorRoute,
} as any)
const AppTutorCurriculumRoute = AppTutorCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AppTutorRoute,
} as any)
const AppTutorMarkingRoute = AppTutorMarkingRouteImport.update({
  id: '/marking',
  path: '/marking',
  getParentRoute: () => AppTutorRoute,
} as any)
const AppTutorResourcesRoute = AppTutorResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppTutorRoute,
} as any)
const AppTutorStudentsStudentIdRoute =
  AppTutorStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AppTutorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/curriculum': typeof AppCurriculumRoute
  '/dashboard': typeof AppDashboardRoute
  '/messages': typeof AppMessagesRoute
  '/plan': typeof AppPlanRoute
  '/planner': typeof AppPlannerRoute
  '/sort': typeof AppSortRoute
  '/tutor': typeof AppTutorRouteWithChildren
  '/homework/$assignmentId': typeof AppHomeworkAssignmentIdRoute
  '/tutor/curriculum': typeof AppTutorCurriculumRoute
  '/tutor/marking': typeof AppTutorMarkingRoute
  '/tutor/resources': typeof AppTutorResourcesRoute
  '/homework/': typeof AppHomeworkIndexRoute
  '/tutor/': typeof AppTutorIndexRoute
  '/tutor/students/$studentId': typeof AppTutorStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/curriculum': typeof AppCurriculumRoute
  '/dashboard': typeof AppDashboardRoute
  '/messages': typeof AppMessagesRoute
  '/plan': typeof AppPlanRoute
  '/planner': typeof AppPlannerRoute
  '/sort': typeof AppSortRoute
  '/homework/$assignmentId': typeof AppHomeworkAssignmentIdRoute
  '/tutor/curriculum': typeof AppTutorCurriculumRoute
  '/tutor/marking': typeof AppTutorMarkingRoute
  '/tutor/resources': typeof AppTutorResourcesRoute
  '/homework': typeof AppHomeworkIndexRoute
  '/tutor': typeof AppTutorIndexRoute
  '/tutor/students/$studentId': typeof AppTutorStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/curriculum': typeof AppCurriculumRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/sort': typeof AppSortRoute
  '/_app/tutor': typeof AppTutorRouteWithChildren
  '/_app/homework/$assignmentId': typeof AppHomeworkAssignmentIdRoute
  '/_app/tutor/curriculum': typeof AppTutorCurriculumRoute
  '/_app/tutor/marking': typeof AppTutorMarkingRoute
  '/_app/tutor/resources': typeof AppTutorResourcesRoute
  '/_app/homework/': typeof AppHomeworkIndexRoute
  '/_app/tutor/': typeof AppTutorIndexRoute
  '/_app/tutor/students/$studentId': typeof AppTutorStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/curriculum'
    | '/dashboard'
    | '/messages'
    | '/plan'
    | '/planner'
    | '/sort'
    | '/tutor'
    | '/homework/$assignmentId'
    | '/tutor/curriculum'
    | '/tutor/marking'
    | '/tutor/resources'
    | '/homework/'
    | '/tutor/'
    | '/tutor/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/curriculum'
    | '/dashboard'
    | '/messages'
    | '/plan'
    | '/planner'
    | '/sort'
    | '/homework/$assignmentId'
    | '/tutor/curriculum'
    | '/tutor/marking'
    | '/tutor/resources'
    | '/homework'
    | '/tutor'
    | '/tutor/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/_app/curriculum'
    | '/_app/dashboard'
    | '/_app/messages'
    | '/_app/plan'
    | '/_app/planner'
    | '/_app/sort'
    | '/_app/tutor'
    | '/_app/homework/$assignmentId'
    | '/_app/tutor/curriculum'
    | '/_app/tutor/marking'
    | '/_app/tutor/resources'
    | '/_app/homework/'
    | '/_app/tutor/'
    | '/_app/tutor/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/curriculum': {
      id: '/_app/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AppCurriculumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sort': {
      id: '/_app/sort'
      path: '/sort'
      fullPath: '/sort'
      preLoaderRoute: typeof AppSortRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutor': {
      id: '/_app/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/homework/': {
      id: '/_app/homework/'
      path: '/homework'
      fullPath: '/homework/'
      preLoaderRoute: typeof AppHomeworkIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/homework/$assignmentId': {
      id: '/_app/homework/$assignmentId'
      path: '/homework/$assignmentId'
      fullPath: '/homework/$assignmentId'
      preLoaderRoute: typeof AppHomeworkAssignmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutor/': {
      id: '/_app/tutor/'
      path: '/'
      fullPath: '/tutor/'
      preLoaderRoute: typeof AppTutorIndexRouteImport
      parentRoute: typeof AppTutorRoute
    }
    '/_app/tutor/curriculum': {
      id: '/_app/tutor/curriculum'
      path: '/curriculum'
      fullPath: '/tutor/curriculum'
      preLoaderRoute: typeof AppTutorCurriculumRouteImport
      parentRoute: typeof AppTutorRoute
    }
    '/_app/tutor/marking': {
      id: '/_app/tutor/marking'
      path: '/marking'
      fullPath: '/tutor/marking'
      preLoaderRoute: typeof AppTutorMarkingRouteImport
      parentRoute: typeof AppTutorRoute
    }
    '/_app/tutor/resources': {
      id: '/_app/tutor/resources'
      path: '/resources'
      fullPath: '/tutor/resources'
      preLoaderRoute: typeof AppTutorResourcesRouteImport
      parentRoute: typeof AppTutorRoute
    }
    '/_app/tutor/students/$studentId': {
      id: '/_app/tutor/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/tutor/students/$studentId'
      preLoaderRoute: typeof AppTutorStudentsStudentIdRouteImport
      parentRoute: typeof AppTutorRoute
    }
  }
}

interface AppTutorRouteChildren {
  AppTutorCurriculumRoute: typeof AppTutorCurriculumRoute
  AppTutorMarkingRoute: typeof AppTutorMarkingRoute
  AppTutorResourcesRoute: typeof AppTutorResourcesRoute
  AppTutorIndexRoute: typeof AppTutorIndexRoute
  AppTutorStudentsStudentIdRoute: typeof AppTutorStudentsStudentIdRoute
}

const AppTutorRouteChildren: AppTutorRouteChildren = {
  AppTutorCurriculumRoute: AppTutorCurriculumRoute,
  AppTutorMarkingRoute: AppTutorMarkingRoute,
  AppTutorResourcesRoute: AppTutorResourcesRoute,
  AppTutorIndexRoute: AppTutorIndexRoute,
  AppTutorStudentsStudentIdRoute: AppTutorStudentsStudentIdRoute,
}

const AppTutorRouteWithChildren = AppTutorRoute._addFileChildren(
  AppTutorRouteChildren,
)

interface AppRouteChildren {
  AppCurriculumRoute: typeof AppCurriculumRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPlanRoute: typeof AppPlanRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppSortRoute: typeof AppSortRoute
  AppTutorRoute: typeof AppTutorRouteWithChildren
  AppHomeworkAssignmentIdRoute: typeof AppHomeworkAssignmentIdRoute
  AppHomeworkIndexRoute: typeof AppHomeworkIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCurriculumRoute: AppCurriculumRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPlanRoute: AppPlanRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppSortRoute: AppSortRoute,
  AppTutorRoute: AppTutorRouteWithChildren,
  AppHomeworkAssignmentIdRoute: AppHomeworkAssignmentIdRoute,
  AppHomeworkIndexRoute: AppHomeworkIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
